import "../styles/global.css";
import "moment/locale/id";

export const metadata = {
  title: "Jadwal Piala Dunia",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        <main className="container min-h-screen">{children}</main>
        <footer className="p-[40px] bg-zinc-100 mt-[10px]">
          Made By Bagus
        </footer>
      </body>
    </html>
  );
}
